### ISSUE TITLE
Support base16-bytestring-1.0

### ISSUE THREAD

**Issue by chris-martin** [wereHamster/avers#452]
The test-suite of [avers](https://hackage.haskell.org/package/avers) depends on base16-bytestring but its upper bound prohibits latest version.

https://github.com/commercialhaskell/stackage/issues/5649

**Comment by wereHamster** [comment]
The dependency was removed from the cabal file a looong time ago (dc0313f8eb1072af9c303c0b5d310988c29fc3f0), but unfortunately I can't remove dependencies via editing the metadata on hackage.haskell.org. So instead I've opened up the version range to allow any version of base16-bytestring.
